global:
  scrape_interval: 15s

scrape_configs:
  - job_name: sqlrite-primary
    static_configs:
      - targets:
          - sqlrite-primary:8099

  - job_name: sqlrite-replica-1
    static_configs:
      - targets:
          - sqlrite-replica-1:8099

  - job_name: sqlrite-replica-2
    static_configs:
      - targets:
          - sqlrite-replica-2:8099
